### ISSUE TITLE
Doesn't work with torch >= 1.0 and 1D data.

### ISSUE THREAD

**Issue by buriy** [facebookresearch/enorm#1]
File "train.py", line 479, in train_batch
    enorm.step()
  File "/Projects/myproj/.venv/lib/python3.6/site-packages/enorm/enorm/enorm.py", line 67, in step
    self._step_conv()
  File "/Projects/myproj/.venv/lib/python3.6/site-packages/enorm/enorm/enorm.py", line 85, in _step_conv
    right_w = self._get_weight(1, 'r')
  File "/Projects/myproj/.venv/lib/python3.6/site-packages/enorm/enorm/enorm.py", line 60, in _get_weight
    param = param.permute(1, 2, 3, 0).contiguous().view(param.size(1), -1)
RuntimeError: number of dims don't match in permute

**Comment by pierrestock** [comment]
Hello, 

Thanks for reaching out! Could you please provide more context? What do you mean by 1D data? What is your training loop? On which architecture do you apply ENorm?

**Comment by buriy** [comment]
Hi Pierre,

I have a convolutional network for audio processing and wanted to make a network like TDNN-F but with ENorm (I guess they should be similar). 
I have 3d tensors, not 4d like in photo processing.
My input is (BATCH_SIZE, N_CHANNELS, N_TIME_STEPS)
Then I have a stack of Conv + ReLU + Dropout.
At the end of the network, I have a custom CTC Loss.

So I guess the problem is that 
.permute(1, 2, 3, 0) fails for my 3d-tensors, but it's best for you as the author to check this.

**Comment by pierrestock** [comment]
Hi Buriy,

Thanks for the details. If I understand you well, your convolutional layer is a 1D convolution (with 3D weights of size C_out x C_in x k)? 

In this case, you could adapt the code as follows:
- update the `_get_weight()` function by replacing `param.permute(1, 2, 3, 0)` by `param.permute(1, 2, 0)`
-  update the `_step_conv()` function by replacing `balancer.unsqueeze(1).unsqueeze(2).unsqueeze(3)` by something like `balancer.unsqueeze(1).unsqueeze(2)` and 
`balancer.unsqueeze(1).unsqueeze(2).unsqueeze(0)` by something like `balancer.unsqueeze(1).unsqueeze(0)` 
- check that you didn't forgot any such replacements (and double-check the dimensions)

As a sanity check, you could then check that your network yields the same output before and after applying ENorm to its weights (for the same given input).

Please let me know if you have any questions!
